//account_id will be generated by Auth0- set value as TEXT
//username TEXT

export const user = [
  {
    username: "Idman123",
  },
  {
    username: "Idman567",
  },
  {
    username: "Idman234",
  },
];
