//account_id will be generated by Auth0- set value as TEXT
//username TEXT

export const user = [
  {
    account_id: 1,
    username: "Idman.a",
  },
  {
    account_id: 2,
    username: "Idman.b",
  },
  {
    account_id: 2,
    username: "Idman.c",
  },
];
